spring:
  application:
    name: caff-backend
  datasource:
    url: "jdbc:h2:file:./data/app"
    username: "sa"
    password: "password"
    driverClassName: "org.h2.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
server:
  error:
    include-message: always
  port: 8087
logging:
  file:
    name: "${spring.application.name}.log"

data:
  allowedOrigin: "http://localhost:3000"

