spring:
  application:
    name: caff_backend
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/testrealm/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/testrealm
  datasource:
    url: "jdbc:mysql://localhost:3306/${spring.application.name}?createDatabaseIfNotExist=true&requireSSL=false&useSSL=false&jdbcCompliantTruncation=false"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
server:
  error:
    include-message: always
  port: 8087
logging:
  file:
    name: "${spring.application.name}.log"

data:
  allowedOrigin: "http://localhost:3000"

keycloak:
  clientId: account
  token_url: http://localhost:8080/auth/realms/testrealm/protocol/openid-connect/token


