#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_jniparser_CAFFParser */

#ifndef _Included_jni_jniparser_CAFFParser
#define _Included_jni_jniparser_CAFFParser
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     jni_jniparser_CAFFParser
	 * Method:    parse
	 * Signature: (Ljava/lang/String;)Ljni/jniparser/CAFFResponse;
	 */
	JNIEXPORT jobject JNICALL Java_jni_jniparser_CAFFParser_parse
	(JNIEnv*, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

